services:
  tortoisebot-ros2-gazebo:
    image: warehouse_rb1_sim
    container_name: warehouse_rb1_sim_cont
    privileged: true
    environment:
      - DISPLAY=:0
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1
      - GAZEBO_MASTER_URI=http://localhost:11345
      - GAZEBO_MODEL_DATABASE_URI=http://models.gazebosim.org
      - OGRE_RTT_MODE=Copy
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg:rw
      - /usr/lib/wsl:/usr/lib/wsl:ro
    network_mode: host